mod_id=ae2logistics
mod_group=io.github.johnhamilto
mod_version=0.12.0

minecraft_version=1.21.1
neoforge_version=21.1.172
ae2_version=19.2.17
guideme_version=21.1.1

loader_version_range=[1,)
neo_version_range=[21.1,)
ae2_version_range=[19.2.0,20.0.0)

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3G
